import { Country, Question, Difficulty } from '../types';
import { TOTAL_QUESTIONS, OPTIONS_PER_QUESTION } from '../constants';

const countries: Country[] = [
    { name: 'Afghanistan', code: 'af', continent: 'Asia' },
    { name: 'Albania', code: 'al', continent: 'Europe' },
    { name: 'Algeria', code: 'dz', continent: 'Africa' },
    { name: 'Andorra', code: 'ad', continent: 'Europe' },
    { name: 'Angola', code: 'ao', continent: 'Africa' },
    { name: 'Argentina', code: 'ar', continent: 'South America' },
    { name: 'Armenia', code: 'am', continent: 'Asia' },
    { name: 'Australia', code: 'au', continent: 'Oceania' },
    { name: 'Austria', code: 'at', continent: 'Europe' },
    { name: 'Azerbaijan', code: 'az', continent: 'Asia' },
    { name: 'Bahamas', code: 'bs', continent: 'North America' },
    { name: 'Bahrain', code: 'bh', continent: 'Asia' },
    { name: 'Bangladesh', code: 'bd', continent: 'Asia' },
    { name: 'Barbados', code: 'bb', continent: 'North America' },
    { name: 'Belarus', code: 'by', continent: 'Europe' },
    { name: 'Belgium', code: 'be', continent: 'Europe' },
    { name: 'Belize', code: 'bz', continent: 'North America' },
    { name: 'Benin', code: 'bj', continent: 'Africa' },
    { name: 'Bhutan', code: 'bt', continent: 'Asia' },
    { name: 'Bolivia', code: 'bo', continent: 'South America' },
    { name: 'Bosnia and Herzegovina', code: 'ba', continent: 'Europe' },
    { name: 'Botswana', code: 'bw', continent: 'Africa' },
    { name: 'Brazil', code: 'br', continent: 'South America' },
    { name: 'Brunei', code: 'bn', continent: 'Asia' },
    { name: 'Bulgaria', code: 'bg', continent: 'Europe' },
    { name: 'Burkina Faso', code: 'bf', continent: 'Africa' },
    { name: 'Burundi', code: 'bi', continent: 'Africa' },
    { name: 'Cambodia', code: 'kh', continent: 'Asia' },
    { name: 'Cameroon', code: 'cm', continent: 'Africa' },
    { name: 'Canada', code: 'ca', continent: 'North America' },
    { name: 'Cape Verde', code: 'cv', continent: 'Africa' },
    { name: 'Central African Republic', code: 'cf', continent: 'Africa' },
    { name: 'Chad', code: 'td', continent: 'Africa' },
    { name: 'Chile', code: 'cl', continent: 'South America' },
    { name: 'China', code: 'cn', continent: 'Asia' },
    { name: 'Colombia', code: 'co', continent: 'South America' },
    { name: 'Comoros', code: 'km', continent: 'Africa' },
    { name: 'Costa Rica', code: 'cr', continent: 'North America' },
    { name: 'Croatia', code: 'hr', continent: 'Europe' },
    { name: 'Cuba', code: 'cu', continent: 'North America' },
    { name: 'Cyprus', code: 'cy', continent: 'Europe' },
    { name: 'Czech Republic', code: 'cz', continent: 'Europe' },
    { name: 'Denmark', code: 'dk', continent: 'Europe' },
    { name: 'Djibouti', code: 'dj', continent: 'Africa' },
    { name: 'Dominica', code: 'dm', continent: 'North America' },
    { name: 'Dominican Republic', code: 'do', continent: 'North America' },
    { name: 'Ecuador', code: 'ec', continent: 'South America' },
    { name: 'Egypt', code: 'eg', continent: 'Africa' },
    { name: 'El Salvador', code: 'sv', continent: 'North America' },
    { name: 'Equatorial Guinea', code: 'gq', continent: 'Africa' },
    { name: 'Estonia', code: 'ee', continent: 'Europe' },
    { name: 'Ethiopia', code: 'et', continent: 'Africa' },
    { name: 'Fiji', code: 'fj', continent: 'Oceania' },
    { name: 'Finland', code: 'fi', continent: 'Europe' },
    { name: 'France', code: 'fr', continent: 'Europe' },
    { name: 'Gabon', code: 'ga', continent: 'Africa' },
    { name: 'Gambia', code: 'gm', continent: 'Africa' },
    { name: 'Georgia', code: 'ge', continent: 'Asia' },
    { name: 'Germany', code: 'de', continent: 'Europe' },
    { name: 'Ghana', code: 'gh', continent: 'Africa' },
    { name: 'Greece', code: 'gr', continent: 'Europe' },
    { name: 'Grenada', code: 'gd', continent: 'North America' },
    { name: 'Guatemala', code: 'gt', continent: 'North America' },
    { name: 'Guinea', code: 'gn', continent: 'Africa' },
    { name: 'Guyana', code: 'gy', continent: 'South America' },
    { name: 'Haiti', code: 'ht', continent: 'North America' },
    { name: 'Honduras', code: 'hn', continent: 'North America' },
    { name: 'Hungary', code: 'hu', continent: 'Europe' },
    { name: 'Iceland', code: 'is', continent: 'Europe' },
    { name: 'India', code: 'in', continent: 'Asia' },
    { name: 'Indonesia', code: 'id', continent: 'Asia' },
    { name: 'Iran', code: 'ir', continent: 'Asia' },
    { name: 'Iraq', code: 'iq', continent: 'Asia' },
    { name: 'Ireland', code: 'ie', continent: 'Europe' },
    { name: 'Israel', code: 'il', continent: 'Asia' },
    { name: 'Italy', code: 'it', continent: 'Europe' },
    { name: 'Jamaica', code: 'jm', continent: 'North America' },
    { name: 'Japan', code: 'jp', continent: 'Asia' },
    { name: 'Jordan', code: 'jo', continent: 'Asia' },
    { name: 'Kazakhstan', code: 'kz', continent: 'Asia' },
    { name: 'Kenya', code: 'ke', continent: 'Africa' },
    { name: 'Kuwait', code: 'kw', continent: 'Asia' },
    { name: 'Kyrgyzstan', code: 'kg', continent: 'Asia' },
    { name: 'Laos', code: 'la', continent: 'Asia' },
    { name: 'Latvia', code: 'lv', continent: 'Europe' },
    { name: 'Lebanon', code: 'lb', continent: 'Asia' },
    { name: 'Liberia', code: 'lr', continent: 'Africa' },
    { name: 'Libya', code: 'ly', continent: 'Africa' },
    { name: 'Liechtenstein', code: 'li', continent: 'Europe' },
    { name: 'Lithuania', code: 'lt', continent: 'Europe' },
    { name: 'Luxembourg', code: 'lu', continent: 'Europe' },
    { name: 'Madagascar', code: 'mg', continent: 'Africa' },
    { name: 'Malawi', code: 'mw', continent: 'Africa' },
    { name: 'Malaysia', code: 'my', continent: 'Asia' },
    { name: 'Maldives', code: 'mv', continent: 'Asia' },
    { name: 'Mali', code: 'ml', continent: 'Africa' },
    { name: 'Malta', code: 'mt', continent: 'Europe' },
    { name: 'Mauritania', code: 'mr', continent: 'Africa' },
    { name: 'Mauritius', code: 'mu', continent: 'Africa' },
    { name: 'Mexico', code: 'mx', continent: 'North America' },
    { name: 'Moldova', code: 'md', continent: 'Europe' },
    { name: 'Monaco', code: 'mc', continent: 'Europe' },
    { name: 'Mongolia', code: 'mn', continent: 'Asia' },
    { name: 'Montenegro', code: 'me', continent: 'Europe' },
    { name: 'Morocco', code: 'ma', continent: 'Africa' },
    { name: 'Mozambique', code: 'mz', continent: 'Africa' },
    { name: 'Myanmar', code: 'mm', continent: 'Asia' },
    { name: 'Namibia', code: 'na', continent: 'Africa' },
    { name: 'Nepal', code: 'np', continent: 'Asia' },
    { name: 'Netherlands', code: 'nl', continent: 'Europe' },
    { name: 'New Zealand', code: 'nz', continent: 'Oceania' },
    { name: 'Nicaragua', code: 'ni', continent: 'North America' },
    { name: 'Niger', code: 'ne', continent: 'Africa' },
    { name: 'Nigeria', code: 'ng', continent: 'Africa' },
    { name: 'North Korea', code: 'kp', continent: 'Asia' },
    { name: 'North Macedonia', code: 'mk', continent: 'Europe' },
    { name: 'Norway', code: 'no', continent: 'Europe' },
    { name: 'Oman', code: 'om', continent: 'Asia' },
    { name: 'Pakistan', code: 'pk', continent: 'Asia' },
    { name: 'Panama', code: 'pa', continent: 'North America' },
    { name: 'Papua New Guinea', code: 'pg', continent: 'Oceania' },
    { name: 'Paraguay', code: 'py', continent: 'South America' },
    { name: 'Peru', code: 'pe', continent: 'South America' },
    { name: 'Philippines', code: 'ph', continent: 'Asia' },
    { name: 'Poland', code: 'pl', continent: 'Europe' },
    { name: 'Portugal', code: 'pt', continent: 'Europe' },
    { name: 'Qatar', code: 'qa', continent: 'Asia' },
    { name: 'Romania', code: 'ro', continent: 'Europe' },
    { name: 'Russia', code: 'ru', continent: 'Europe' },
    { name: 'Rwanda', code: 'rw', continent: 'Africa' },
    { name: 'San Marino', code: 'sm', continent: 'Europe' },
    { name: 'Saudi Arabia', code: 'sa', continent: 'Asia' },
    { name: 'Senegal', code: 'sn', continent: 'Africa' },
    { name: 'Serbia', code: 'rs', continent: 'Europe' },
    { name: 'Sierra Leone', code: 'sl', continent: 'Africa' },
    { name: 'Singapore', code: 'sg', continent: 'Asia' },
    { name: 'Slovakia', code: 'sk', continent: 'Europe' },
    { name: 'Slovenia', code: 'si', continent: 'Europe' },
    { name: 'Somalia', code: 'so', continent: 'Africa' },
    { name: 'South Africa', code: 'za', continent: 'Africa' },
    { name: 'South Korea', code: 'kr', continent: 'Asia' },
    { name: 'South Sudan', code: 'ss', continent: 'Africa' },
    { name: 'Spain', code: 'es', continent: 'Europe' },
    { name: 'Sri Lanka', code: 'lk', continent: 'Asia' },
    { name: 'Sudan', code: 'sd', continent: 'Africa' },
    { name: 'Sweden', code: 'se', continent: 'Europe' },
    { name: 'Switzerland', code: 'ch', continent: 'Europe' },
    { name: 'Syria', code: 'sy', continent: 'Asia' },
    { name: 'Taiwan', code: 'tw', continent: 'Asia' },
    { name: 'Tanzania', code: 'tz', continent: 'Africa' },
    { name: 'Thailand', code: 'th', continent: 'Asia' },
    { name: 'Togo', code: 'tg', continent: 'Africa' },
    { name: 'Trinidad and Tobago', code: 'tt', continent: 'North America' },
    { name: 'Tunisia', code: 'tn', continent: 'Africa' },
    { name: 'Turkey', code: 'tr', continent: 'Asia' },
    { name: 'Turkmenistan', code: 'tm', continent: 'Asia' },
    { name: 'Uganda', code: 'ug', continent: 'Africa' },
    { name: 'Ukraine', code: 'ua', continent: 'Europe' },
    { name: 'United Arab Emirates', code: 'ae', continent: 'Asia' },
    { name: 'United Kingdom', code: 'gb', continent: 'Europe' },
    { name: 'United States', code: 'us', continent: 'North America' },
    { name: 'Uruguay', code: 'uy', continent: 'South America' },
    { name: 'Uzbekistan', code: 'uz', continent: 'Asia' },
    { name: 'Venezuela', code: 've', continent: 'South America' },
    { name: 'Vietnam', code: 'vn', continent: 'Asia' },
    { name: 'Yemen', code: 'ye', continent: 'Asia' },
    { name: 'Zambia', code: 'zm', continent: 'Africa' },
    { name: 'Zimbabwe', code: 'zw', continent: 'Africa' },
];

const shuffleArray = <T,>(array: T[]): T[] => {
  return [...array].sort(() => Math.random() - 0.5);
};

export const generateQuiz = (difficulty: Difficulty): Question[] => {
  const shuffledCountries = shuffleArray(countries);
  const quizCountries = shuffledCountries.slice(0, TOTAL_QUESTIONS);

  return quizCountries.map((correctCountry) => {
    const numOptions = OPTIONS_PER_QUESTION[difficulty];
    const otherOptions = shuffleArray(countries.filter(c => c.code !== correctCountry.code)).slice(0, numOptions - 1);
    const options = shuffleArray([...otherOptions.map(c => c.name), correctCountry.name]);

    return {
      flagUrl: `https://flagcdn.com/${correctCountry.code}.svg`,
      options,
      correctAnswer: correctCountry.name,
      hint: `Continent: ${correctCountry.continent}`,
    };
  });
};
